{
 "title": "Drone Status",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Drone Current Pending",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "drone_build_pending_current", "legendFormat": "{{repo}}" }
   ]
  },
  {
   "title": "Drone Current Killed",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "targets": [
    { "expr": "drone_build_kill_total" }
   ]
  },
  {
   "title": "Drone Current Running",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 0 },
   "targets": [
    { "expr": "drone_build_running_current", "legendFormat": "{{repo}}" }
   ]
  },
  {
   "title": "Drone Failure Current",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "drone_build_failure_current", "legendFormat": "{{repo}}" }
   ]
  },
  {
   "title": "Current Running App Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(server) (drone_build_running_current)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Drone Success Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(drone_build_success_total)",
     "legendFormat": "{{repo}}"
    }
   ]
  }
 ]
}